### ISSUE TITLE
Exception has occurred: Attribute Error module 'inspect' has no attribute 'getargspec'

### ISSUE THREAD

**Issue by eyadagg** [Nem4/viewerbot#73]
getting this > Exception has occurred: Attribute Error module 'inspect' has no attribute 'getargspec'

**Comment by rowdyslav** [comment]
+

Traceback (most recent call last):
  File "C:\Users\rowdyslav\Рабочий стол\viewerbot-master\threads_viewer.py", line 2, in <module>
    from streamlink import Streamlink
  File "D:\Programming Langs\Python311\Lib\site-packages\streamlink\__init__.py", line 73, in <module>
    from .api import streams
  File "D:\Programming Langs\Python311\Lib\site-packages\streamlink\api.py", line 1, in <module>
    from .session import Streamlink
  File "D:\Programming Langs\Python311\Lib\site-packages\streamlink\session.py", line 11, in <module>
    from streamlink.logger import StreamlinkLogger, Logger
  File "D:\Programming Langs\Python311\Lib\site-packages\streamlink\logger.py", line 7, in <module>
    from streamlink.compat import is_py2
  File "D:\Programming Langs\Python311\Lib\site-packages\streamlink\compat.py", line 58, in <module>
    getargspec = getattr(inspect, "getfullargspec", inspect.getargspec)
                                                    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
